language: node_js
node_js: '10'

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron

os:
- linux
- osx

osx_image: xcode10

addons:
  apt:
    packages:
    - fakeroot
    - rpm

before_script:
- >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # On OSX, pull the cert from a base64 env var
      export CERTIFICATE_P12=certificates/Certificate.p12;
      echo $CERTIFICATE_OSX_P12 | base64 --decode > $CERTIFICATE_P12;
      # Create a new OSX keychain (we can't access the travis default)
      export KEYCHAIN=httptoolkit-build.keychain;
      export KEYCHAIN_PASSWORD=mynotverysecretpassword
      security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN;
      security default-keychain -s $KEYCHAIN;
      security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN;
      # Try and make code signing work reliably, see
      # https://docs.travis-ci.com/user/common-build-problems/#mac-os-x-mavericks-109-code-signing-errors
      # https://docs.travis-ci.com/user/common-build-problems/#mac-macos-sierra-1012-code-signing-errors
      security set-keychain-settings -t 3600 -u $KEYCHAIN
      security import $CERTIFICATE_P12 -k $KEYCHAIN -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign;
      security set-key-partition-list -S apple-tool:,apple: -s -k $KEYCHAIN_PASSWORD $KEYCHAIN
    fi

script:
- npm run make

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: out/make/*.{zip,deb,dmg}
  skip_cleanup: true
  on:
    repo: httptoolkit/httptoolkit-desktop
    tags: true