name: CI
on: push
jobs:
  build:
    name: Build & test
    strategy:
      matrix:
        os: [
          "ubuntu-18.04",
          "windows-2019",
          "macos-10.15"
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - run: npm ci

      - run: npm run build
        env:
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

      - uses: actions/upload-artifact@v2
        with:
          name: distributables
          path: |
            dist/*.exe
            dist/*.deb
            dist/*.dmg
          if-no-files-found: error